export const FETCH_POSTS_REQUEST = "FETCH_WEATHER_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_WEATHER_FAILURE";
export const GET_POST = "GET_POST";
